parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Pulsar\PulsarProducer:
        arguments:
            $uri: 'pulsar://pulsar:6650'
            $topic: 'persistent://public/default/poc'

    App\Controller\ApiTestController:
        autoconfigure: true
        autowire: false
        arguments:
            $pulsarProducer: '@App\Pulsar\PulsarProducer'

    App\Console\:
        resource: '%kernel.project_dir%/src/Console/*Command.php'
        autoconfigure: true
        autowire: false
        bind:
            $pulsarProducer: '@App\Pulsar\PulsarProducer'

