parameters:
    pulsar_uri: '%env(PULSAR_URI)%'
    pulsar_topic: '%env(PULSAR_TOPIC)%'
    pulsar_subscription_name: '%env(PULSAR_SUBSCRIPTION_NAME)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Pulsar\PulsarProducer:
        arguments:
            $uri: '%pulsar_uri%'
            $topic: '%pulsar_topic%'

    App\Pulsar\PulsarConsumer:
        arguments:
            $uri: '%pulsar_uri%'
            $topic: '%pulsar_topic%'
            $subscriptionName: '%pulsar_subscription_name%'

    App\Controller\ApiTestController:
        autoconfigure: true
        autowire: false
        arguments:
            $pulsarProducer: '@App\Pulsar\PulsarProducer'

    App\Console\:
        resource: '%kernel.project_dir%/src/Console/*Command.php'
        autoconfigure: true
        autowire: false
        bind:
            $pulsarProducer: '@App\Pulsar\PulsarProducer'
            $pulsarConsumer: '@App\Pulsar\PulsarConsumer'

